default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  timeout: 5000
  username: <%= Rails.application.credentials.db.username %>
  password: <%= Rails.application.credentials.db.password %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: igaku-rails-backend_development
test:
  <<: *default
  database: igaku-rails-backend_test
production:
  <<: *default
  database: igaku-rails-backend_production
  username: igaku-rails-backend
  password: <%= ENV['IGAKU-RAILS-BACKEND_DATABASE_PASSWORD'] %>
