default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  timeout: 5000
  username: <%= ENV['db_username'] %>
  password: <%= ENV['db_password'] %>

development:
  <<: *default
  database: igaku_rails_backend_development
test:
  <<: *default
  database: igaku_rails_backend_test
  username: <%= ENV['db_username'] %>
  password: <%= ENV['db_password'] %>
production:
  <<: *default
  database: igaku_rails_backend_production
  username: igaku-rails-backend
  password: <%= ENV['db_password'] %>
